env:
  global:
  - TERM=dumb
language: java
jdk: oraclejdk8
install: true
before_install:
- sudo apt update -y || true
- sudo apt install -y --no-install-recommends git bash
script:
- git clone https://github.com/daggerok/github-pages-gitbook-gradle.git gitbook-example
- cd gitbook-example/gitbook
- bash gradlew clean gitbook
