env:
  global:
  - TERM=dumb
language: java
jdk: oraclejdk8
install: true
before_install:
- sudo apt update -y || true >/dev/null 2>&1
- sudo apt install -y --no-install-recommends git bash >/dev/null 2>&1
script:
- export root=$(pwd)
- git clone https://github.com/daggerok/spring-integration-5-examples.git $root/gitbook-example
- cd $root/gitbook-example
- bash gradlew clean gitbook
- ls -lah $root/gitbook-example/gitbook/build
- ls -lah $root/gitbook-example/gitbook/build/gitbook
